### declare system parameters

In [10]:
import numpy as np
np.set_printoptions(precision=5, suppress=True)

In [11]:
K = 0.01
J = 0.01
b = 0.01
R = 1
L = 0.5
r = 0.05
h_ref = 10
V_ref = 10

### system dynamics

In [12]:
dt = 1/10.0

Ac = np.array([[0, -r, 0],
              [0, -b/J, K/J],
              [0, -K/L, -R/L]])

Bc = np.array([[0,0],
              [-1/J, 0],
              [0, 1/L]])
C = np.array([[V_ref/h_ref, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

Ad = np.eye(3) + dt*Ac
Bd = dt*Bc

### current state and variances

In [13]:
u = np.array([1, 10])
var_u = 0.01

x_now = np.array([2, 11, 10])
var_x = 0.02

z_now = np.array([1.98*h_ref/V_ref, 11.1, 9.96])
var_z = 0.1

### predictiction step

In [14]:
x_bar = Ad@x_now + Bd@u
S_xbar = Ad @ np.eye(3)*var_x @ Ad.T + Bd @ np.eye(2)*var_u @ Bd.T

S_xbar

array([[ 0.02   , -0.00009,  0.     ],
       [-0.00009,  1.0164 ,  0.00156],
       [ 0.     ,  0.00156,  0.0132 ]])

### Kalman Gain

In [15]:
K = S_xbar @ C.T @ np.linalg.inv(C @ S_xbar @ C.T + np.eye(3)*var_z)
K

array([[ 0.16667, -0.00007,  0.     ],
       [-0.00007,  0.91042,  0.00124],
       [ 0.     ,  0.00124,  0.11659]])

### Innovation step

In [16]:
x_next = x_bar + K@(z_now - C@x_bar)
x_next

array([ 1.95015, 10.18631,  9.98852])

In [17]:
S_xnext = (np.eye(3) - K@C)@S_xbar
S_xnext

array([[ 0.01667, -0.00001,  0.     ],
       [-0.00001,  0.09104,  0.00012],
       [ 0.     ,  0.00012,  0.01166]])