In [1]:
import numpy as np
from sympy import *
np.set_printoptions(precision=4, suppress=True)

In [2]:
px, py = symbols("p_x p_y")
h = sqrt((4 - px)**2 + (5 - py)**2)
Hx = h.diff(Matrix([px,py]))
simplify(Hx)

Matrix([
[(p_x - 4)/sqrt((p_x - 4)**2 + (p_y - 5)**2)],
[(p_y - 5)/sqrt((p_x - 4)**2 + (p_y - 5)**2)]])

In [74]:
x_bar = np.array([1,1])
Sigmax_bar = np.array([[0.2**2 , 0.1*0.2**2],
                       [0.1*0.2**2, 0.2**2]])
Sigmaz = 0.1**2

Hx = np.array(Hx.subs({px: 1, py: 1})).astype(np.float64).flatten()
K = Sigmax_bar @ Hx.T * 1/(Hx @ Sigmax_bar @ Hx.T + Sigmaz)
K

array([-0.5052, -0.6389])

In [75]:
x = x_bar + K * (4.8 - 5)
x

array([1.101 , 1.1278])

In [76]:
### posterior sigmax
(np.eye(2) - K @ Hx) @ Sigmax_bar

array([[ 0.0042, -0.0318],
       [-0.0318,  0.0042]])

In [77]:
### part c
px, py = symbols("p_x p_y")
h = sqrt((4 - px)**2 + (5 - py)**2)
Hx = h.diff(Matrix([px,py]))
simplify(Hx)

x_bar = np.array([1,1])
Sigmax_bar = np.array([[0.2**2 , 0.1*0.2**2],
                       [0.1*0.2**2, 0.2**2]])
Sigmaz = 0.5**2
Hx = np.array(Hx.subs({px: 1, py: 1})).astype(np.float64).flatten()
K = Sigmax_bar @ Hx.T * 1/(Hx @ Sigmax_bar @ Hx.T + Sigmaz)
x = x_bar + K * (4.8 - 5)
x

array([1.0185, 1.0234])

In [78]:
### sigmax post
(np.eye(2) - K @ Hx) @ Sigmax_bar

array([[ 0.0334, -0.0026],
       [-0.0026,  0.0334]])