In [1]:
import numpy as np
from sympy import *
np.set_printoptions(precision=4, suppress=True)

In [2]:
L = 9
x = Matrix([1, 0.9, -3.9, 8.487])
Sigma = Matrix.diag([0.1**2, 0.2**2, 0.5**2, 0.5**2])
lam = 2
kappa = 0 # chosen
beta = 2 # chosen

x0 = x

x1 = (x + ((L+lam)*Sigma).pow(0.5)[0,:].T)
x2 = (x + ((L+lam)*Sigma).pow(0.5)[1,:].T)
x3 = (x + ((L+lam)*Sigma).pow(0.5)[2,:].T)
x4 = (x + ((L+lam)*Sigma).pow(0.5)[3,:].T)

x5 = (x - ((L+lam)*Sigma).pow(0.5)[0,:].T)
x6 = (x - ((L+lam)*Sigma).pow(0.5)[1,:].T)
x7 = (x - ((L+lam)*Sigma).pow(0.5)[2,:].T)
x8 = (x - ((L+lam)*Sigma).pow(0.5)[2,:].T)

In [3]:
pprint(x0.transpose())
pprint(x1.transpose())
pprint(x2.transpose())
pprint(x3.transpose())
pprint(x4.transpose())
pprint(x5.transpose())
pprint(x6.transpose())
pprint(x7.transpose())
pprint(x8.transpose())

[1  0.9  -3.9  8.487]
[1.33166247903554  0.9  -3.9  8.487]
[1  1.56332495807108  -3.9  8.487]
[1  0.9  -2.2416876048223  8.487]
[1  0.9  -3.9  10.1453123951777]
[0.66833752096446  0.9  -3.9  8.487]
[1  0.23667504192892  -3.9  8.487]
[1  0.9  -5.5583123951777  8.487]
[1  0.9  -5.5583123951777  8.487]
